# Generated by Django 2.1.4 on 2019-12-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_history_weight', models.IntegerField()),
                ('trash_history_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tloaction_name', models.CharField(max_length=100)),
                ('tlocation_x', models.IntegerField()),
                ('tlocation_y', models.IntegerField()),
                ('tlocation_weight', models.IntegerField()),
                ('tlocation_hight', models.IntegerField()),
                ('tpub_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='trashhistory',
            name='trash_can_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lora_garbage_app.TrashInfo'),
        ),
    ]
