# Generated by Django 2.1.4 on 2019-12-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lora_garbage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashhistory',
            name='trash_history_time',
            field=models.DateField(auto_now=True),
        ),
    ]
