# Generated by Django 2.1.4 on 2019-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lora_garbage_app', '0002_trashhistory_trash_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashhistory',
            name='trash_history_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
