# Generated by Django 2.1.4 on 2020-01-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lora_garbage_app', '0003_auto_20191223_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashinfo',
            name='send_email_bit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trashinfo',
            name='tloaction_name',
            field=models.CharField(max_length=100, verbose_name='location_name'),
        ),
    ]
